### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Granada\ORM' not found

### ISSUE THREAD

**Issue by navotera** [GranadaORM/Granada#16]
Hello 

I want to install this library using the provided installation instruction however, it cannot succeed : 
![image](https://user-images.githubusercontent.com/1424851/97251129-43d6f080-1842-11eb-9bb3-7a9a35b1f3f1.png)

![image](https://user-images.githubusercontent.com/1424851/97251147-4b969500-1842-11eb-80a0-61985520ff74.png)

Thank you for any suggestions.

**Comment by joshbmarshall** [comment]
Thanks for the issue report. It looks like the autoload configuration was not compatible with Composer v2.
I've released a new version that works with Composer 2.
