### ISSUE TITLE
Try to change ParisORM to GrandaORM

### ISSUE THREAD

**Issue by navotera** [GranadaORM/Granada#17]
Thank for fixing the error the class load error on our previous report. 

Seem like I find another error. 
This library makes it won't automatically find the function based **on the camelCase or underscore**, in which on the original ParisORM these all are supported function such as : 

findMany, findOne and others function. 
`Message: no static findMany found or static method 'filter_findMany' not defined`

Thank you

**Comment by joshbmarshall** [comment]
I have re-implemented the camelCase to underscore.

**Comment by navotera** [comment]
This work fine on findMany but error on findOne : 
![image](https://user-images.githubusercontent.com/1424851/97398244-d13f4100-1925-11eb-8ee9-7395e2a54367.png)

The error vanish when I using find_one(); 

example : 
Table::findOne() --> error 
Table::find_one() --> get it right
Please check

**Comment by navotera** [comment]
I also want to ask. 
On Paris findMany if nothing is found will return nothing / empty / false. But on this library, it will return an array with index 0. 
Can you explain what is the consideration of this? 

Thank you so much.

**Comment by joshbmarshall** [comment]
if you run:

```php
foreach (Table::find_many() as $item) {
}
```
Then it doesn't work if find_many() returns false.

**Comment by joshbmarshall** [comment]
If you're having a problem with findOne() please give a good example of it failing, see https://github.com/GranadaORM/Granada/blob/master/tests/orm/CamelCaseTest.php it shows findOne() working correctly.

**Comment by navotera** [comment]
This is the error : 
![image](https://user-images.githubusercontent.com/1424851/97402875-4ca4f080-192e-11eb-88ba-ad9f31d89a4f.png)

This is the simple code : 
https://pastebin.com/cz5Rme3A

**Comment by navotera** [comment]
I also find a weird result that when relations runs using findOne and find_one it returns different query result : 

code : 
```
Class Rtlh extends Model

  public function sumber_dana()
    {
        return  $this->belongs_to('RtlhSumberDanaORM', 'sumber_dana_id');
    }

}

$Rtlh->sumber_dana()->findOne();
//query result : 
SELECT * FROM `rtlh_sumber_dana` WHERE `id` = '4' AND `id` = LIMIT 1


$Rtlh->sumber_dana()->find_one();
//query result : 
SELECT * FROM `rtlh_sumber_dana` WHERE `id` = '4' LIMIT 1

```

**Comment by joshbmarshall** [comment]
I've released a new version that fixes this issue :)

**Comment by navotera** [comment]
This is awesome!
Thank you @joshbmarshall 

I will keep  you posted to improve this library 👍

**Comment by navotera** [comment]
Hello Josh 

When I get the result for findMany and doing for each : 

```
$data = Table::findMany();
foreach($data => $key as $item) 
```

the key becomes the id of the item not the index of the array. This is different from Paris since key or the index of the array can be used to add numbers to the table list. 
Is there any reason for this behavior? 

Thank you.

**Comment by joshbmarshall** [comment]
Hi I did not develop this library, I have inherited it from the original author. I can see that it is done on purpose in ORM.php _get_instances() function. 

But it is a configuration item to use the array index instead. Use the following to get back to what ParisORM provides:

`\Granada\ORM::configure('find_many_primary_id_as_key', false);`

I found this by searching the source code - it's something I didn't know :smile:

**Comment by navotera** [comment]
Thank you so much @joshbmarshall  for you valuable information and contribution for this library. 

I think this should be false by default as it on ParisORM. 

Thank you.

**Comment by joshbmarshall** [comment]
Unfortunately changing a default means it we would have to release a breaking change version as some people would be relying on the current GranadaORM default. But at least you know how to make it compatible with what you are using it for.

**Comment by navotera** [comment]
Thank you so much Josh
I understand.
